import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("../../", import.meta.url));
const schemaRoot = join(root, "packages/contracts/schemas");
const catalog = JSON.parse(await readFile(join(schemaRoot, "catalog.v1.json"), "utf8"));
const source = JSON.stringify(catalog, null, 2) + "\n";
const hash = createHash("sha256").update(source).digest("hex");
const target = join(root, "packages/contracts/src/generated/v1.ts");
const output = `// Generated by tools/codegen/generate.mjs. DO NOT EDIT.\n// Contract: 1.0.0\n// Source SHA-256: ${hash}\nexport const CONTRACT_SCHEMA_KINDS = ${JSON.stringify(catalog.schemas.map((entry) => entry.kind))} as const;\nexport type ContractSchemaKind = (typeof CONTRACT_SCHEMA_KINDS)[number];\n`;
const check = process.argv.includes("--check");
if (check) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error("generated contract artifacts are stale");
    process.exit(1);
  }
} else {
  await mkdir(join(root, "packages/contracts/src/generated"), { recursive: true });
  await writeFile(target, output);
  console.log(`generated ${target}`);
}
